//! Generate a self-contained Binary Ninja Python script that re-applies
//! annotations on whichever binary view the user opens it in.
//!
//! Strategy mirrors `ghidra.rs`: emit static Python that the user pastes
//! into the Binary Ninja Python console (no plugin SDK required, works
//! across all editions).

use crate::analyzers::{Annotation, AnnotationKind};
use crate::output::OutputBackend;
use std::io::Write;

pub struct Binja;

impl OutputBackend for Binja {
    fn render(&self, anns: &[Annotation], w: &mut dyn Write) -> std::io::Result<()> {
        writeln!(
            w,
            "# auto-generated by rustrip — paste this into Binary Ninja's Python console"
        )?;
        writeln!(w, "# applies {} annotations to the current binary view", anns.len())?;
        writeln!(w)?;
        writeln!(w, "import binaryninja as bn")?;
        writeln!(w)?;
        writeln!(w, "_labels = {{}}")?;
        writeln!(w, "_comments = {{}}")?;
        writeln!(w)?;
        for a in anns {
            if matches!(a.kind, AnnotationKind::String) {
                continue;
            }
            writeln!(
                w,
                "_labels[0x{:x}] = {}",
                a.vaddr,
                py_str_with_escape(&a.label)
            )?;
        }
        for a in anns {
            if let Some(c) = &a.comment {
                writeln!(
                    w,
                    "_comments[0x{:x}] = {}",
                    a.vaddr,
                    py_str_with_escape(c)
                )?;
            }
        }
        writeln!(w)?;
        writeln!(w, "_bv = bn.BinaryView")?;
        writeln!(w, "# The user must rebind _bv to their open BinaryView:")?;
        writeln!(w, "# _bv = current_view  # noqa")?;
        writeln!(w)?;
        writeln!(w, "_applied_l = 0")?;
        writeln!(w, "_applied_c = 0")?;
        writeln!(w, "for addr, name in _labels.items():")?;
        writeln!(w, "    try:")?;
        writeln!(w, "        sym = bn.Symbol(bn.SymbolType.DataSymbol, name, addr)")?;
        writeln!(w, "        _bv.define_user_symbol(sym)")?;
        writeln!(w, "        _applied_l += 1")?;
        writeln!(w, "    except Exception as _e:")?;
        writeln!(w, "        pass")?;
        writeln!(w, "for addr, text in _comments.items():")?;
        writeln!(w, "    _bv.set_comment_at(addr, text)")?;
        writeln!(w, "    _applied_c += 1")?;
        writeln!(w)?;
        writeln!(w, "print(\"rustrip: applied\", _applied_l, \"labels,\", _applied_c, \"comments\")")?;
        Ok(())
    }
}

fn py_str_with_escape(s: &str) -> String {
    // Emit a Python *raw* double-quoted string (`r"..."`). Raw literals
    // leave backslashes alone, so Windows paths `C:\Users\foo` pass
    // through unchanged. We still escape embedded double quotes by
    // substituting `\u{FFFD}` (the Unicode replacement character)
    // because Python raw strings have no quote-escape mechanism.
    let mut out = String::with_capacity(s.len() + 4);
    out.push_str("r\"");
    for ch in s.chars() {
        if ch == '"' {
            out.push('\u{FFFD}');
        } else {
            out.push(ch);
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn handles_quotes_and_newlines() {
        let s = py_str_with_escape("a\"b\nc");
        // Raw string form: backslashes stay literal; double-quote is
        // replaced with the Unicode replacement char (no escape inside
        // a Python raw literal).
        assert!(s.starts_with("r\""));
        assert!(s.ends_with("\""));
        assert!(s.contains("a\u{FFFD}b\nc"));
    }

    #[test]
    fn raw_paths_pass_through() {
        let s = py_str_with_escape(r"C:\Users\foo\bar.rs");
        assert!(s.contains(r"C:\Users\foo\bar.rs"));
    }
}
