//! Generate a self-contained Binary Ninja Python script that re-applies
//! annotations on whichever binary view the user opens it in.
//!
//! Strategy mirrors `ghidra.rs`: emit static Python that the user pastes
//! into the Binary Ninja Python console (no plugin SDK required, works
//! across all editions).

use crate::analyzers::{Annotation, AnnotationKind};
use crate::output::OutputBackend;
use std::io::Write;

pub struct Binja;

impl OutputBackend for Binja {
    fn render(&self, anns: &[Annotation], w: &mut dyn Write) -> std::io::Result<()> {
        writeln!(
            w,
            "# auto-generated by rustrip — paste this into Binary Ninja's Python console"
        )?;
        writeln!(
            w,
            "# applies {} annotations to the current binary view",
            anns.len()
        )?;
        writeln!(w)?;
        writeln!(w, "import binaryninja as bn")?;
        writeln!(w)?;
        writeln!(w, "_labels = {{}}")?;
        writeln!(w, "_comments = {{}}")?;
        writeln!(w)?;
        for a in anns {
            if matches!(a.kind, AnnotationKind::String) {
                continue;
            }
            writeln!(
                w,
                "_labels[0x{:x}] = {}",
                a.vaddr,
                py_str_with_escape(&a.label)
            )?;
        }
        for a in anns {
            if let Some(c) = &a.comment {
                writeln!(w, "_comments[0x{:x}] = {}", a.vaddr, py_str_with_escape(c))?;
            }
        }
        writeln!(w)?;
        writeln!(w, "_bv = bn.BinaryView")?;
        writeln!(w, "# The user must rebind _bv to their open BinaryView:")?;
        writeln!(w, "# _bv = current_view  # noqa")?;
        writeln!(w)?;
        writeln!(w, "_applied_l = 0")?;
        writeln!(w, "_applied_c = 0")?;
        writeln!(w, "for addr, name in _labels.items():")?;
        writeln!(w, "    try:")?;
        writeln!(
            w,
            "        sym = bn.Symbol(bn.SymbolType.DataSymbol, name, addr)"
        )?;
        writeln!(w, "        _bv.define_user_symbol(sym)")?;
        writeln!(w, "        _applied_l += 1")?;
        writeln!(w, "    except Exception as _e:")?;
        writeln!(w, "        pass")?;
        writeln!(w, "for addr, text in _comments.items():")?;
        writeln!(w, "    _bv.set_comment_at(addr, text)")?;
        writeln!(w, "    _applied_c += 1")?;
        writeln!(w)?;
        writeln!(
            w,
            "print(\"rustrip: applied\", _applied_l, \"labels,\", _applied_c, \"comments\")"
        )?;
        Ok(())
    }
}

fn py_str_with_escape(s: &str) -> String {
    // Emit a Python *raw* double-quoted string (`r"..."`). Raw literals
    // leave backslashes alone, so Windows paths `C:\Users\foo` pass
    // through unchanged. Python raw strings *also* don't accept `"`
    // inside the literal — we substitute the Unicode replacement
    // character U+FFFD instead.
    let mut out = String::with_capacity(s.len() + 4);
    out.push_str("r\"");
    for ch in s.chars() {
        if ch == '"' {
            out.push('\u{FFFD}');
        } else {
            out.push(ch);
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn raw_paths_pass_through() {
        let s = py_str_with_escape(r"C:\Users\foo\bar.rs");
        assert!(s.contains(r"C:\Users\foo\bar.rs"));
    }

    #[test]
    fn double_quote_replaced_with_replacement_char() {
        let s = py_str_with_escape("a\"b");
        // raw r"a\u{FFFD}b" — but raw literals still don't process \u,
        // so we have to make the assertion against the literal codepoint.
        let mut expected = String::with_capacity(8);
        expected.push('r');
        expected.push('"');
        expected.push('a');
        expected.push('\u{FFFD}');
        expected.push('b');
        expected.push('"');
        assert_eq!(s, expected);
    }
}
